<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Lazuli</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/ext/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/resources/css/auth.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/resources/LunchPack/lunch.css" />
        <link href="/favicon.ico" rel="favicon" >
        <script type="text/javascript" src="/resources/LunchPack/lunch.js" ></script>
        <script type="text/javascript" src="/ext/ext-all.js" ></script>
        <script type="text/javascript" src="/src/auth/bootstrap.js" ></script>
    </head>

    <body>
        <div id="back-toppage">
            <a href="/test" >トップページへ戻る</a>
        </div>

        <div id="signin-form"></div>
        <div id="hidden-csrf" class="x-hidden"><?php echo $this->token ?></div>
    </body>

</html>
