<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Lazuli</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/ext/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/resources/css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/resources/css/syntax/SyntaxHighlighter.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/resources/LunchPack/lunch.css" />
        <link href="/favicon.ico" rel="favicon" >
        <script type="text/javascript" src="/resources/js/syntax/shCore.js"></script>
        <script type="text/javascript" src="/resources/js/syntax/shBrushJScript.js"></script>
        <script type="text/javascript" src="/resources/js/syntax/shBrushXml.js"></script>
        <script type="text/javascript" src="/resources/LunchPack/lunch.js" ></script>
        <script type="text/javascript" src="/ext/ext-all.js" ></script>
        <script type="text/javascript" src="/src/app/bootstrap.js" ></script>
        <script type="text/javascript" src="/api.php" ></script>
    </head>

    <body>
        <div id="auth-container">
            <a href="/test/auth/"><img src="/resources/images/auth/icon.png" /></a>
        </div>

        <h1 id="site-title"><a href="" >Lazuli</a></h1>

        <div id="contents-container"></div>
    </body>

</html>
